{
  description = "Jimmy's Nix Darwin Configuration - Modern, Modular, Production-Ready";

  # ============================================
  # INPUTS - External Dependencies
  # ============================================

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    nix-darwin = {
      url = "github:LnL7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Secrets management
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Optional: nix-darwin-kickstarter patterns
    # Uncomment if you want additional community modules
    # nix-homebrew.url = "github:zhaofengli-wip/nix-homebrew";
  };

  # ============================================
  # OUTPUTS - System Configurations
  # ============================================

  outputs = inputs@{ self, nix-darwin, home-manager, nixpkgs, sops-nix }:
    let
      # ============================================
      # HELPER IMPORTS
      # ============================================

      # Import custom lib functions (see nix-config/lib/README.md)
      myLib = import ./nix-config/lib { inherit inputs; };

      # Import overlays for package customizations
      overlays = import ./nix-config/overlays { inherit inputs; };

      # ============================================
      # USER & MACHINE CONFIG (required)
      # ============================================
      # These files are generated by configure.sh and gitignored.
      # They MUST exist before building the system.

      userConfig =
        let
          # Use absolute path to config file (outside flake store)
          # This allows gitignored configs to be imported
          flakeRoot = builtins.getEnv "FLAKE_ROOT";
          configPath =
            if flakeRoot != ""
            then flakeRoot + "/config/user-config.nix"
            else "/Users/jimmy/nix-darwin/config/user-config.nix";
        in
        if builtins.pathExists (builtins.toPath configPath)
        then import (builtins.toPath configPath)
        else throw ''
          config/user-config.nix not found at: ${configPath}

          Run the configuration script first:
            ./configure.sh
        '';

      machineConfig =
        let
          # Use absolute path to config file (outside flake store)
          flakeRoot = builtins.getEnv "FLAKE_ROOT";
          configPath =
            if flakeRoot != ""
            then flakeRoot + "/config/machine-config.nix"
            else "/Users/jimmy/nix-darwin/config/machine-config.nix";
        in
        if builtins.pathExists (builtins.toPath configPath)
        then import (builtins.toPath configPath)
        else throw ''
          config/machine-config.nix not found at: ${configPath}

          Run the configuration script first:
            ./configure.sh
        '';

      # ============================================
      # PROFILE-BASED CONFIGURATION
      # ============================================
      # Extract values from machine config for profile system

      profileName = machineConfig.profileName or "personal";
      machineId = machineConfig.machineId or "default";
      system = machineConfig.system or "aarch64-darwin";
      expectedHostname = machineConfig.expectedHostname or machineId;

      # ============================================
      # SYSTEM BUILDER HELPER (LEGACY)
      # ============================================
      # Legacy builder for backward compatibility during transition.
      # New systems should use profile-based configuration below.

      mkDarwinSystem = { hostname, system ? "aarch64-darwin", username, mixins ? [] }:
        let
          # DEPRECATED: Use profile-based configuration instead
          # This is kept for backward compatibility only
          machineType = profileName;  # Use profileName from machine config
        in
        nix-darwin.lib.darwinSystem {
          inherit system;
          specialArgs = {
            inherit inputs username hostname myLib machineType;
          };
          modules = [
            # Apply overlays to nixpkgs
            { nixpkgs.overlays = overlays; }

            # Host-specific configuration (uses machineId)
            ./nix-config/hosts/${machineId}

            # System modules
            ./nix-config/modules/darwin
            ./nix-config/modules/shared

            # Home Manager integration
            home-manager.darwinModules.home-manager
            {
              home-manager = {
                useGlobalPkgs = true;
                useUserPackages = true;
                users.${username} = import ./nix-config/home/_template;
                extraSpecialArgs = {
                  inherit inputs mixins hostname myLib machineType username;
                };
                verbose = true;
                backupFileExtension = "hm-backup";
              };
            }

            # Secrets management
            sops-nix.darwinModules.sops
          ];
        };
    in
    {
      # ============================================
      # MACHINE CONFIGURATIONS (PROFILE-BASED)
      # ============================================
      # Primary configuration indexed by machineId

      darwinConfigurations."${machineId}" = nix-darwin.lib.darwinSystem {
        inherit system;

        specialArgs = {
          inherit inputs myLib profileName machineId;
          hostname = expectedHostname;
          username = userConfig.username;
          machineType = profileName;  # Use profileName directly (personal/work/minimal)
        };

        modules = [
          # Apply overlays to nixpkgs
          { nixpkgs.overlays = overlays; }

          # Host-specific configuration (uses machineId)
          ./nix-config/hosts/${machineId}

          # System modules
          ./nix-config/modules/darwin
          ./nix-config/modules/shared

          # Home Manager integration
          home-manager.darwinModules.home-manager
          {
            home-manager = {
              useGlobalPkgs = true;
              useUserPackages = true;
              extraSpecialArgs = {
                inherit inputs myLib profileName machineId userConfig;
                hostname = expectedHostname;
                username = userConfig.username;
                machineType = profileName;  # Use profileName directly (personal/work/minimal)
              };

              users.${userConfig.username} = { config, pkgs, ... }: {
                imports = [
                  ./nix-config/home/_template
                  ./nix-config/home/_profiles/${profileName}
                ];
              };

              verbose = true;
              backupFileExtension = "hm-backup";
            };
          }

          # Secrets management
          sops-nix.darwinModules.sops
        ];
      };

      # ============================================
      # BACKWARD COMPATIBILITY ALIASES
      # ============================================
      # Allow building with hostname for smooth transition
      # Usage: darwin-rebuild switch --flake .#mbp-jimmy

      darwinConfigurations."mbp-jimmy" = self.darwinConfigurations."${machineId}";
      darwinConfigurations."mbp-work" = self.darwinConfigurations."${machineId}";

      # ============================================
      # LIBRARY EXPORTS
      # ============================================
      # Expose custom functions and helpers for external use.
      # Access with: nix eval .#lib.<function>

      lib = myLib // {
        inherit mkDarwinSystem;
      };

      # ============================================
      # VALIDATION & INTROSPECTION EXPORTS
      # ============================================
      # These exports are used by git hooks and validation scripts.

      # Secret file paths and patterns (for git hook validation)
      # Usage: nix eval .#secretPaths --json
      secretPaths = myLib.secrets.secretPaths;
      secretGlobPatterns = myLib.secrets.secretGlobPatterns;
      secretsByType = myLib.secrets.secretsByType;

      # Machine type detection (for validation and testing)
      # Usage: nix eval .#currentMachineType --json
      currentMachineType = myLib.machineType (builtins.getEnv "HOSTNAME");

      # Profile information (for validation)
      # Usage: nix eval .#activeProfile --json
      activeProfile = profileName;
      activeMachineId = machineId;
    };
}
