{
  description = "Jimmy's Nix Darwin Configuration - Modern, Modular, Production-Ready";

  # ============================================
  # INPUTS - External Dependencies
  # ============================================

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    nix-darwin = {
      url = "github:LnL7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Secrets management
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Optional: nix-darwin-kickstarter patterns
    # Uncomment if you want additional community modules
    # nix-homebrew.url = "github:zhaofengli-wip/nix-homebrew";
  };

  # ============================================
  # OUTPUTS - System Configurations
  # ============================================

  outputs = inputs@{ self, nix-darwin, home-manager, nixpkgs, sops-nix }:
    let
      # ============================================
      # HELPER IMPORTS
      # ============================================

      # Import custom lib functions (see nix-config/lib/README.md)
      myLib = import ./nix-config/lib { inherit inputs; };

      # Import overlays for package customizations
      overlays = import ./nix-config/overlays { inherit inputs; };

      # ============================================
      # USER & MACHINE CONFIG (required)
      # ============================================
      # These files are generated by configure.sh and gitignored.
      # They MUST exist before building the system.

      userConfig =
        let
          # Use absolute path to config file (outside flake store)
          # This allows gitignored configs to be imported
          flakeRoot = builtins.getEnv "FLAKE_ROOT";
          configPath =
            if flakeRoot != ""
            then flakeRoot + "/config/user-config.nix"
            else "/Users/jimmy/nix-darwin/config/user-config.nix";
        in
        if builtins.pathExists (builtins.toPath configPath)
        then import (builtins.toPath configPath)
        else throw ''
          config/user-config.nix not found at: ${configPath}

          Run the configuration script first:
            ./configure.sh
        '';

      machineConfig =
        let
          # Use absolute path to config file (outside flake store)
          flakeRoot = builtins.getEnv "FLAKE_ROOT";
          configPath =
            if flakeRoot != ""
            then flakeRoot + "/config/machine-config.nix"
            else "/Users/jimmy/nix-darwin/config/machine-config.nix";
        in
        if builtins.pathExists (builtins.toPath configPath)
        then import (builtins.toPath configPath)
        else throw ''
          config/machine-config.nix not found at: ${configPath}

          Run the configuration script first:
            ./configure.sh
        '';

      # ============================================
      # APPS - Run Scripts via Nix
      # ============================================
      # Usage: nix run .#<app-name>

      apps.${system} = {
        health = {
          type = "app";
          program = "${self}/scripts/maintenance/health-check.sh";
        };
        audit = {
          type = "app";
          program = "${self}/scripts/validation/audit-permissions.sh";
        };
        test = {
          type = "app";
          program = "${self}/tests/run-all-tests.sh";
        };
      };

      # ============================================
      # PROFILE-BASED CONFIGURATION
      # ============================================
      # Extract values from machine config for profile system

      profileName = machineConfig.profileName or machineConfig.machineType or "personal";
      machineId = machineConfig.machineId or "default";
      system = machineConfig.system or "aarch64-darwin";
      expectedHostname = machineConfig.expectedHostname or machineId;
      enableHomeManager = machineConfig.enableHomeManager or true;
      skipGoPackages = machineConfig.skipGoPackages or false;

    in
    {
      # ============================================
      # MACHINE CONFIGURATIONS (PROFILE-BASED)
      # ============================================
      # Primary configuration indexed by machineId

      darwinConfigurations."${machineId}" = nix-darwin.lib.darwinSystem {
        inherit system;

        specialArgs = {
          inherit inputs myLib profileName machineId enableHomeManager skipGoPackages;
          hostname = expectedHostname;
          username = userConfig.username;
          machineType = profileName;  # Use profileName directly (personal/work/minimal)
        };

        modules = [
          # Apply overlays to nixpkgs
          { nixpkgs.overlays = overlays; }

          # Secrets management (must be loaded before host config)
          sops-nix.darwinModules.sops

          # Host-specific configuration (uses machineId)
          ./nix-config/hosts/${machineId}

          # System modules
          ./nix-config/modules/darwin
          ./nix-config/modules/shared
        ]
        # Conditionally add Home Manager integration
        ++ (if enableHomeManager then [
          home-manager.darwinModules.home-manager
          {
            home-manager = {
              useGlobalPkgs = true;
              useUserPackages = true;
              extraSpecialArgs = {
                inherit inputs myLib profileName machineId userConfig skipGoPackages;
                hostname = expectedHostname;
                username = userConfig.username;
                machineType = profileName;  # Use profileName directly (personal/work/minimal)
              };

              users.${userConfig.username} = { config, pkgs, ... }: {
                imports = [
                  ./nix-config/home/_template
                  ./nix-config/home/_profiles/${profileName}
                ];
              };

              verbose = true;
              backupFileExtension = "hm-backup";
            };
          }
        ] else [
          # Warning module when home-manager is disabled
          {
            warnings = [
              ''
                Home-Manager is DISABLED (enableHomeManager = false)
                - No user-level shell/git/program configuration
                - Only system-wide packages and settings will be applied
                - To re-enable: Set enableHomeManager = true in config/machine-config.nix
              ''
            ];
          }
        ]);
      };

      # ============================================
      # LIBRARY EXPORTS
      # ============================================
      # Expose custom functions and helpers for external use.
      # Access with: nix eval .#lib.<function>

      lib = myLib;

      # ============================================
      # VALIDATION & INTROSPECTION EXPORTS
      # ============================================
      # These exports are used by git hooks and validation scripts.

      # Secret file paths and patterns (for git hook validation)
      # Usage: nix eval .#secretPaths --json
      secretPaths = myLib.secrets.secretPaths;
      secretGlobPatterns = myLib.secrets.secretGlobPatterns;
      secretsByType = myLib.secrets.secretsByType;



      # Profile information (for validation)
      # Usage: nix eval .#activeProfile --json
      activeProfile = profileName;
      activeMachineId = machineId;
    };
}
