#!/usr/bin/env bash
# configure.sh
#
# Generate machine and user configuration files

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

echo "=== Minimal Nix-Darwin Configuration Setup ==="
echo ""

# Check if configs already exist
if [ -f "${CONFIG_ROOT}/config/user-config.nix" ] && [ -f "${CONFIG_ROOT}/config/machine-config.nix" ]; then
    echo "Existing configuration found."
    echo ""
    read -p "Reconfigure? This will overwrite existing configs. (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        exit 0
    fi
    echo ""
fi

# User configuration
echo "User Configuration"
echo "------------------"
echo ""

read -p "Username [$USER]: " username
username=${username:-$USER}

read -p "Full name: " fullname
read -p "Email: " email

echo ""

# Machine configuration
echo "Machine Configuration"
echo "---------------------"
echo ""

# Get hostname
current_hostname=$(hostname -s)
read -p "Machine ID [$current_hostname]: " machineid
machineid=${machineid:-$current_hostname}

echo ""
echo "Machine type:"
echo "  1. personal (default)"
echo "  2. work"
read -p "Choose [1]: " machine_type_choice
machine_type_choice=${machine_type_choice:-1}

case $machine_type_choice in
    2)
        machine_type="work"
        ;;
    *)
        machine_type="personal"
        ;;
esac

read -p "Machine description [$machineid]: " description
description=${description:-$machineid}

echo ""
echo "Summary"
echo "-------"
echo "Username:     $username"
echo "Full name:    $fullname"
echo "Email:        $email"
echo "Machine ID:   $machineid"
echo "Machine type: $machine_type"
echo "Description:  $description"
echo ""

read -p "Create configuration files? (Y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Nn]$ ]]; then
    echo "Cancelled."
    exit 0
fi

# Create configs
mkdir -p "${CONFIG_ROOT}/config"

# User config
cat > "${CONFIG_ROOT}/config/user-config.nix" << EOF
# user-config.nix
#
# User-specific configuration
# Generated by scripts/setup/configure.sh

{
  username = "${username}";
  fullName = "${fullname}";
  email = "${email}";
}
EOF

# Machine config
cat > "${CONFIG_ROOT}/config/machine-config.nix" << EOF
# machine-config.nix
#
# Machine-specific configuration
# Generated by scripts/setup/configure.sh

{
  machineId = "${machineid}";
  machineType = "${machine_type}";
  description = "${description}";
}
EOF

echo ""
echo "✓ Configuration files created:"
echo "  ${CONFIG_ROOT}/config/user-config.nix"
echo "  ${CONFIG_ROOT}/config/machine-config.nix"
echo ""
echo "Next step:"
echo "  ./scripts/setup/activate.sh"
echo ""
