# Proxy Configuration for Corporate Environments
#
# This file is NOT gitignored and can be committed to the repository.
# It contains proxy URLs and settings needed for corporate network access.
#
# Used by: work profiles to configure Go, Python, NPM proxies
# Source: Generated by configure.sh for work machines

{
  # Go module proxy (for sops-nix and other Go-based tools)
  go = {
    enabled = true;
    url = "https://nexus.example.com/repository/duke-cne-golang/";
    private = "github.com/examplecorp-corp/";
  };

  # Python package proxy (configure if needed)
  python = {
    enabled = false;
    url = "";
    trustedHost = "";
  };

  # NPM package proxy (configure if needed)
  npm = {
    enabled = false;
    url = "";
  };
}
