{
  description = "Minimal nix-darwin - Modular package management without Home Manager";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nix-darwin = {
      url = "github:LnL7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs@{ self, nix-darwin, nixpkgs }:
    let
      # Import machine and user configs
      # These files are gitignored and generated by configure.sh
      machineConfig = if builtins.pathExists ./config/machine-config.nix
        then import ./config/machine-config.nix
        else {
          machineId = "default-machine";
          machineType = "personal";
          description = "Default machine config";
        };

      userConfig = if builtins.pathExists ./config/user-config.nix
        then import ./config/user-config.nix
        else {
          username = builtins.getEnv "USER";
          fullName = "User";
          email = "user@example.com";
        };

      # Flake root for scripts
      flakeRoot = builtins.toString ./.;

      configuration = { pkgs, ... }: {
        # Import modules
        imports = [
          ./modules/shared/packages.nix
          ./modules/shared/nix.nix
          ./modules/darwin/system.nix
          ./modules/darwin/fonts.nix
          ./modules/darwin/homebrew.nix
          ./modules/darwin/security.nix
        ];

        # Pass configs to modules
        _module.args = {
          inherit machineConfig userConfig flakeRoot;
        };

        # Set hostname from machine config
        networking.hostName = machineConfig.machineId;

        # Ensure user exists
        users.users.${userConfig.username} = {
          home = "/Users/${userConfig.username}";
          shell = pkgs.zsh;
        };

        # Enable zsh (but don't manage config)
        programs.zsh.enable = true;

        # This is required
        system.stateVersion = 5;
      };
    in
    {
      darwinConfigurations.${machineConfig.machineId} = nix-darwin.lib.darwinSystem {
        modules = [ configuration ];
      };

      # Default configuration (for `darwin-rebuild switch --flake .`)
      darwinConfigurations.default = nix-darwin.lib.darwinSystem {
        modules = [ configuration ];
      };
    };
}
