#!/usr/bin/env bash
# Migrate secrets from old host directory to new
#
# Usage: ./scripts/migrate-secrets.sh

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[i]${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }
warning() { echo -e "${YELLOW}⚠${NC} $1"; }
error() { echo -e "${RED}✗${NC} $1"; }

# Configuration
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OLD_SECRETS=".temp/deprecated/hosts/mbp-jimmy/secrets.yaml"
NEW_SECRETS_DIR="nix-config/hosts/macbook-pro-m1"
NEW_SECRETS="$NEW_SECRETS_DIR/secrets.yaml"
AGE_KEY="$HOME/.config/sops/age/keys.txt"
TEMP_OLD="/tmp/old-secrets-decrypted.yaml"
TEMP_NEW="/tmp/new-secrets-decrypted.yaml"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Secrets Migration Script"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
info "This script migrates secrets from old host directory to new"
info "Old secrets can be decrypted with -d but not edited directly (different .sops.yaml)"
echo ""

# Check prerequisites
info "Checking prerequisites..."

if [ ! -f "$AGE_KEY" ]; then
    error "Age key not found at $AGE_KEY"
    exit 1
fi
success "Age key found"

if [ ! -f "$REPO_ROOT/$OLD_SECRETS" ]; then
    error "Old secrets file not found at $OLD_SECRETS"
    exit 1
fi
success "Old secrets file found"

if [ ! -f "$REPO_ROOT/$NEW_SECRETS" ]; then
    error "New secrets file not found at $NEW_SECRETS"
    exit 1
fi
success "New secrets file found"

if ! command -v sops &> /dev/null; then
    error "sops command not found"
    exit 1
fi
success "sops installed"

echo ""

# Decrypt old secrets
info "Decrypting old secrets..."
export SOPS_AGE_KEY_FILE="$AGE_KEY"

if ! sops -d "$REPO_ROOT/$OLD_SECRETS" > "$TEMP_OLD" 2>/dev/null; then
    error "Failed to decrypt old secrets"
    exit 1
fi
success "Old secrets decrypted"

# Decrypt new secrets
info "Decrypting new secrets..."
if ! sops -d "$REPO_ROOT/$NEW_SECRETS" > "$TEMP_NEW" 2>/dev/null; then
    error "Failed to decrypt new secrets"
    rm -f "$TEMP_OLD"
    exit 1
fi
success "New secrets decrypted"

echo ""
info "Analyzing secrets..."
echo ""

# Extract keys from old file
OLD_KEYS=$(grep -E "^[a-z_]+:" "$TEMP_OLD" | cut -d: -f1 | grep -v "_placeholder" || true)

echo "Keys found in old secrets:"
for key in $OLD_KEYS; do
    echo "  • $key"
done

echo ""
info "Merging secrets..."
echo ""

# Create merged secrets file starting with header
cat > /tmp/merged-secrets.yaml << 'EOF'
# Merged secrets from old configuration
# Generated by migrate-secrets.sh

EOF

# Copy the entire old secrets file, stripping the old header
grep -v '^#' "$TEMP_OLD" | grep -v '^$' | head -1 > /tmp/header_check

# Find where actual content starts (after comments)
awk '
BEGIN { in_content = 0 }
/^[a-z_]+:/ { in_content = 1 }
in_content { print }
' "$TEMP_OLD" >> /tmp/merged-secrets.yaml

success "Merged all secrets from old configuration"

echo ""
warning "⚠ IMPORTANT: Review merged secrets before encrypting"
echo ""
echo "Merged secrets preview:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
head -20 /tmp/merged-secrets.yaml
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Backup current new secrets
BACKUP_FILE="$REPO_ROOT/$NEW_SECRETS.backup-$(date +%Y%m%d-%H%M%S)"
cp "$REPO_ROOT/$NEW_SECRETS" "$BACKUP_FILE"
success "Backed up current secrets to: $BACKUP_FILE"

echo ""
read -p "Apply merged secrets to $NEW_SECRETS? [y/N]: " confirm

if [[ ! $confirm =~ ^[Yy]$ ]]; then
    warning "Cancelled - no changes made"
    rm -f "$TEMP_OLD" "$TEMP_NEW" /tmp/merged-secrets.yaml
    exit 0
fi

# Encrypt merged secrets
info "Encrypting merged secrets..."
# Copy to target location first (so path regex matches)
cp /tmp/merged-secrets.yaml "$REPO_ROOT/$NEW_SECRETS"
if ! sops -e -i "$REPO_ROOT/$NEW_SECRETS"; then
    error "Failed to encrypt merged secrets"
    warning "Restoring backup..."
    cp "$BACKUP_FILE" "$REPO_ROOT/$NEW_SECRETS"
    rm -f "$TEMP_OLD" "$TEMP_NEW" /tmp/merged-secrets.yaml
    exit 1
fi

success "Secrets migrated and encrypted successfully!"

# Cleanup
rm -f "$TEMP_OLD" "$TEMP_NEW" /tmp/merged-secrets.yaml

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Migration Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "  1. Verify secrets: SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt sops -d $NEW_SECRETS"
echo "  2. Edit if needed: SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt sops $NEW_SECRETS"
echo "  3. Run activation: ./scripts/activate.sh"
echo ""
